### ISSUE TITLE
Inconsistency between package.json and package-lock.json?

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/eslint-config#106]
The package versions inside package.json differ from the versions inside package-lock.json, which got updated by recent merge requests. Is this by intention or should this be fixed?

i.e. eslint-webpack-plugin
#98 vs. https://github.com/nextcloud/eslint-config/blob/dcbf6ac4614f2ca2b9fa7860b07fe0e8026cc128/package.json#L35

**Comment by skjnldsv** [comment]
https://docs.npmjs.com/about-semantic-versioning

**Comment by skjnldsv** [comment]
![image](https://user-images.githubusercontent.com/14975046/116204533-27f2cf80-a73d-11eb-93a2-fc05115bff88.png)
