### ISSUE TITLE
Missing peer dependency `eslint-webpack-plugin`?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/eslint-config#241]
Ref https://github.com/nextcloud/files_automatedtagging/pull/506#issuecomment-972637074

Since the update from 6.0 to 6.1 the tagging app can not build on CI anymore. It works locally, but I might have the package installed globally or so?

**Comment by artonge** [comment]
https://github.com/nextcloud/eslint-config/commit/aebf1c2273ef858aca59c866bf7b49c5efca1c54#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by artonge** [comment]
Included here: https://github.com/nextcloud/webpack-vue-config/blob/924cf31722db5020e0b3d93ae0cf9e227aa817ac/package.json#L52 so it should be fine to not have it in the repo

**Comment by nickvergessen** [comment]
Well it's still failing in the app repositories for me. Anything I need to do there?🤔

**Comment by skjnldsv** [comment]
ref https://github.com/nextcloud/files_automatedtagging/pull/524
