### ISSUE TITLE
package.json does not allow to use current node/npm versions

### ISSUE THREAD

**Issue by nursoda** [nextcloud/eslint-config#305]
When trying to build my nextcloud app on Arch, I got

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/eslint-config@7.0.2',
npm WARN EBADENGINE   required: { node: '^14.0.0', npm: '^7.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.6.0', npm: '8.5.2' }
npm WARN EBADENGINE }
```

In fact, nextcloud-eslint-config 7.0.2 `package.json` requires

```
	"engines": {
		"node": "^14.0.0",
		"npm": "^7.0.0"
	}
```

I had a hard time finding a way to downgrade everything to suit this since the latest node 14.x comes with npm 6.x, and upgrading to latest npm results in 8.5.2… I used the latest npm 7.x from node 16.10 and combined it with node 14.19 to build. However, even with these 'latest allowed' versions I get security issues from GitHub for my build. Today, latest ['Active' LTS](https://nodejs.org/en/about/releases/) (since 2021-10-26) for node is 16.14, which includes npm 8.3.1…

Is that constraint a technical necessity? If not, could you please also allow for newer [versions](https://nodejs.dev/learn/semantic-versioning-using-npm/), like

```
	"engines": {
		"node": ">=14.0.0",
		"npm": ">=7.0.0"
	}
```

or at least to something similar as this?

```
	"engines": {
		"node": "^14.0.0 || ^15.0.0 || ^16.0.0 || ^17.0.0",
		"npm": "^7.0.0 || ^8.0.0"
	}
```

**Comment by skjnldsv** [comment]
> Is that constraint a technical necessity? If not, could you please also allow for newer [versions](https://nodejs.dev/learn/semantic-versioning-using-npm/), like
> 
> ```
> 	"engines": {
> 		"node": ">=14.0.0",
> 		"npm": ">=7.0.0"
> 	}
> ```

Yes, we actually went from the `>=` operator to `^`. We cannot test all environments and node evolves quite quickly.
We (dev) often change from apps to apps at nextcloud, and it's safer/easier to properly target a version and ensure compatibility with it, rather than switching from one to the other for each repo where some might be compatible or not (we already have a few repo stuck on npm 6)

I suggest you use nvm, it's an easy way to switch versions.
Otherwise do like us and  stay with NC's mostly-global env of node 14 and npm 7 :)

**Comment by nursoda** [comment]
While I understand your point that you cannot test everything, I still vote to (1) support the latest LTS versions or at least (2) use a combination of node and npm that may be achieved by an "nvm install". There is no such combination since all node 14 versions are packaged with nvm < 7.

**Comment by skjnldsv** [comment]
I would be up bumping all versions, but the initial point still stands, we need to be consistent across nextcloud :)
