### ISSUE TITLE
Enforce object-shorthand

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/eslint-config#35]
I would propose to enforce using the object-shorthand rule, see https://eslint.org/docs/rules/object-shorthand. Currently both versions are accepted which seems inconsistent:

```js
methods: {
	methodLong: function() {
		callMethod({ test: test })
	},
	methodShort() {
		callMethod({ test })
	},
}
```

@nextcloud/javascript @nextcloud/vuejs 

Should I send a PR?

**Comment by ChristophWurst** [comment]
I don't have strong feelings on this one. But I guess more consistency is a good thing :+1:

**Comment by raimund-schluessler** [comment]
I tested it for Tasks, and it showed quite a few inconsistencies: https://github.com/nextcloud/tasks/pull/990. And if I am not wrong we try to use the object-shorthand in most apps already. I will send a PR.

**Comment by skjnldsv** [comment]
Same, good to me :)

**Comment by gary-kim** [comment]
I like it. Let's do it!

**Comment by korelstar** [comment]
I like the option `consistent-as-needed` since a general enforcement could lead to hardly readable code.

**Comment by raimund-schluessler** [comment]
> I like the option `consistent-as-needed` since a general enforcement could lead to hardly readable code.

Do you have an example where using shorthand leads to hardly readable code?

**Comment by raimund-schluessler** [comment]
PR is in #36.
